services:
  mysql:
    image: mysql:8.0
    container_name: oship-sample-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql                # 컨테이너 종료 후에도 데이터를 로컬에 저장하여 유지
      - ./db/mysql/init:/docker-entrypoint-initdb.d   # 해당 경로에 작성된 DDL을 컨테이너 생성 시 자동실행
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234

  redis:
    image: redis:7.2
    container_name: oship-sample-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
